version: "3.8"

services:
  app:
    image: python:3.12-slim
    container_name: python_app
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "pip install -r requirements.txt && apt-get update && apt-get install -y ocrmypdf tesseract-ocr-vie && python main.py"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis

  api:
    image: golang:1.23.1-alpine
    ports:
      - "8080:8080"
    container_name: go_api
    volumes:
      - ./api:/src
    working_dir: /src
    command: sh -c "go mod download && go run main.go"
    environment:
      - GO111MODULE=on
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
